### ISSUE TITLE
setup.py fails

### ISSUE THREAD

**Issue by DamienCassou** [tBaxter/vobject#13]
I'm trying to package your vobject in my distribution ([nix](http://nixos.org/nix/)). However, the default handling of python packages fails with the error below. Your `setup.py` references a `test_vobject` module that can't be found.

```
running build_ext
Traceback (most recent call last):
  File "setup.py", line 73, in <module>
    Topic :: Text Processing""".strip().splitlines()
  File "python3.4-distutils.cfg/lib/python3.4/site-packages/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "python3.4-distutils.cfg/lib/python3.4/site-packages/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "python3.4-distutils.cfg/lib/python3.4/site-packages/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setuptools-18.2/lib/python3.4/site-packages/setuptools-18.2-py3.4.egg/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "setuptools-18.2/lib/python3.4/site-packages/setuptools-18.2-py3.4.egg/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "setuptools-18.2/lib/python3.4/site-packages/setuptools-18.2-py3.4.egg/setuptools/command/test.py", line 163, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "python3-3.4.3/lib/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "python3-3.4.3/lib/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "python3-3.4.3/lib/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "python3-3.4.3/lib/python3.4/unittest/loader.py", line 146, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "python3-3.4.3/lib/python3.4/unittest/loader.py", line 146, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "python3-3.4.3/lib/python3.4/unittest/loader.py", line 105, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named 'test_vobject'
builder for ‘/nix/store/xyj0gb5yczw89w5gi7rhhqfd0vlhfrrz-python3.4-vobject-0.8.3.drv’ failed with exit code 1
```

**Comment by tBaxter** [comment]
Resolved with https://github.com/tBaxter/vobject/commit/213f647071e367c234c944eb1de027d739566cbf
